export interface Student {
  regNo?: string; // Optional because it might be generated by the backend or empty initially
  rollNo: number;
  name: string;
  standard: string;
  school: string;
  gender: string;
  percentage: number;
}